SELECT ugb.TITLE
     , ugb.BOARD_ID
     , ugr.REPLY_ID
     , ugr.WRITER_ID
     , ugr.CONTENTS
     , TO_CHAR(ugr.CREATED_DATE,'YYYY-MM-DD') AS "CREATED_DATE"
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_REPLY ugr ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE ugb.CREATED_DATE 
BETWEEN TO_DATE('2022-10-01','YYYY-MM-DD') AND TO_DATE('2022-10-31','YYYY-MM-DD')
ORDER BY ugr.CREATED_DATE, ugb.TITLE;